version: '3.8'

services:
  api_gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      [
        "python3",
        "-u",
        "main.py"
      ]
    container_name: api_gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"