version: '3.8'

services:
  wildberries_service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      [
        "python3",
        "-u",
        "main.py"
      ]
    container_name: wildberries_service
    ports:
      - "${WILDBERRIES_PARSER_API_PORT}:${WILDBERRIES_PARSER_API_PORT}"