version: '3.8'

services:
  parser_website:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true